truncate table vocabulary;
INSERT INTO vocabulary (`word`, `reading`, `mean_en`, `mean_vn`, `description`, `category_id`, `type_id`, `word_type`)
VALUES

-- type:1 -> lập trình
('フロントエンド','','Frontend','Xử lý UI','','1','1',2)
,('バックエンド','','Backend','Xử lý server','','1','1',2)
,('ピーエッチピー','','','PHP','','1','1',2)
,('エーピーアイ','','','API','','1','1',2)
,('ジェーイエス','','','JS','','1','1',2)
,('スクリプト','','Script','Kịch bản','','1','1',2)
,('エッチティエムエル','','','HTML','','1','1',2)
,('シーエスエス','','','CSS','','1','1',2)
,('ケーキピーエッチピー','','','CakePHP','','1','1',2)
,('ファルコン','','','Phalcon','','1','1',2)
,('アンカー','','Anchor','Neo sắt, mấu neo','','1','1',2)
,('洗い出す','あらいだす','Filter','Lọc, Làm rõ','','1','1',1)
,('絞込み','しぼりこみ','Narrow down','Lọc','','1','1',1)
,('フィルタ','','Filter','Lọc','','1','1',1)
,('バージョン','','Version','Phiên bản','','1','1',2)
,('プロトコル','','Protocol','Giao thức','','1','1',2)
,('ソースコード','','Source code','Mã nguồn','','1','1',2)
,('レジストリ','','Registry','Cơ quan đăng ký','','1','1',2)
,('フォーマット','','Format','Dạng mẫu','','1','1',2)
,('引数','ひきかえ','Argument','Trao đổi','','1','1',1)
,('初期値','しょきち','Initial value','Giá trị khởi tạo,giá trị ban đầu','','1','1',1)
,('実数','じっすう','Real number','Số thực','','1','1',1)
,('再現','さいげん','Reappearance','Tái hiện lại','','1','1',1)
,('文のネスト','ぶんのネスト','','Vòng lặp if lồng nhau','','1','1',3)
,('ノットイコール','','Not Equal','Khác','','1','1',2)
,('小なり','こなり','','Nhỏ hơn (<)','','1','1',1)
,('小なりイコール','こなり','','Nhỏ hơn hoặc bằng (<=)','','1','1',3)
,('イコール','','Equal','Bằng (=)','','1','1',2)
,('大なり','おおなり','','Lớn hơn (>)','','1','1',1)
,('大なりイコール','おおなりイコール','','Lớn hơn hoặc bằng (>=)','','1','1',3)
,('ロールバック','','Roll back','Lui lại, lùi về','','1','1',2)
,('バグ','','Bug','Lỗi','','1','1',2)
,('障害','しょうがい','Obstacle','Lỗi','','1','1',1)
,('不具合','ふぐあい','Trouble','Lỗi','','1','1',1)
,('成分','せいぶん','Component','Thành phần','','1','13',1)
,('ポーネント','','Component','Thành phần cấu thành, cấu tạo, hợp','','1','13',2)
,('コンボーネント','','Console','Bảng điều khiển','','1','1',2)
,('コンソールア','','Console','Bảng điều khiển','','1','1',2)
,('プロパティ','','Property','Thuộc tính','','1','1',2)
,('マップ','','Map','Bản đồ','','1','13',2)
,('取引','とりひき','Transaction','Giao tác, chuyển tác','','1','1',1)
,('トランザクション','','Transaction','Giao tác, chuyển tác','','1','1',2)
,('木をパースする','きをパースする','','Duyệt cây','','1','1',3)
,('メールパーザ','','Mail parser','Duyệt mail','','1','1',2)
,('イベント','','Event','Sự kiện','','1','1',2)
,('演算子','えんさんし','Operator','Phép tính (+、-、÷、×)','','1','1',1)
,('アーキテクチャー','','Architecture','Cấu trúc','','1','1',2)
,('プログラミング','','Programming','Lập Trình','','1','1',2)

-- type:2 -> Data
,('データベース','','Database','Cơ sở dữ liệu','','1','1',2)
,('エスキューエル','','SQL','SQL','','1','1',2)
,('表','おもて','Table','Bảng','','1','2',1)
,('テーブル','','Table','Bảng','','1','2',1)
,('列','れつ','Row','Cột','','1','2',1)
,('ロー','','Row','Cột','','1','2',1)
,('行','ぎょう','Line','Dòng','','1','2',1)
,('コラム','','Column','Cột','','1','2',2)
,('レコード','','Record','Sự ghi lại, cột','','1','2',2)
,('主レコードキー','しゅレコードキー','','Khóa chính','','1','2',3)
,('フィルード','','Field','Trường, miền, phạm vi','','1','2',2)
,('外部キー','がいぶキー','Foreign key','Khóa bên ngoài','','1','2',3)
,('リレーショナル','','Relational','Có quan hệ','','1','2',2)
,('コネ','','Connection','Sự nối, liên hệ','','1','2',2)
,('アスタリスク','','Asterisk','Dấu hoa thị','','1','2',2)
,('モーダル','','Modal','Đối thoại theo kiểu','','1','2',2)

-- type:3 -> Website
,('ウェブ','','Web','Lưới','','1','1',2)
,('スパン','','Span','vùng','','1','3',2)
,('スライド','','Slide','Dời, chuyển, trượt','lịch, thời gian, trượt hình ảnh','1','3',2)
,('先頭','せんとう','Header','Phần đầu trang','','1','3',1)
,('ヘッダ','','Header','Phần đầu trang','','1','3',2)
,('フッター','','Footer','Phần cuối trang','','1','3',2)
,('外観','がいかん','Appearance','Giao diện','','1','3',1)
,('多言語化','たげんごか','Multilingualization','Đa ngôn ngữ','','1','3',1)
,('背景','はいけい','Background','Nền','','1','3',1)
,('著作権','ちょさくけん','Copyright','Bản quyền','','1','3',1)
,('コピーライト','','Copyright','Bản quyền','','1','3',2)
,('ライセンス','','License','Bản quyền','','1','3',2)
,('お問い合わせ','おといあわせ','Contact Us','Liên hệ','','1','3',1)
,('ホーム','','Home','Trang chủ','','1','3',2)
,('トップページへ','','Top page','Lên đầu trang','','1','3',2)
,('ユーザビリティ','','Usability','Tính khả dụng','','1','3',2)
,('グラフィック','','Graphic','Đồ hoạ','','1','3',2)
,('アクセシビリティ','','Accessibility','Khả năng truy cập web','','1','3',2)
,('ECサイト','','EC Site','Trang web thương mại điện tử','','1','3',2)
,('余白','よはく','Margin','Khoảng cách, lề giấy','','1','3',1)
,('マージン','','Margin','Khoảng cách, lề giấy','','1','3',2)
,('ノングリッド','','Non-grid','Không có grid','','1','3',1)
,('セクション','','Section','Khu vực, phần','','1','3',2)
,('スクロール','','Scroll','Di chuột, kéo chuột','','1','3',2)
,('フォント','','','Font','','1','3',3)
,('代替フォント','だいたい〜','Alternative font','Font chữ thay thế','','1','3',3)
,('コンテンツ','','Content','Nội dung trang web','','1','3',2)
,('ドメイン','','Domain','Tên miền','','1','3',2)
,('ブラウザ','','Browser','Trình duyệt, chế độ browser','','1','3',3)
,('背景色','はいけいいろ','Background color','Màu phông nền phụ','','1','3',1)
,('背景画像','はいけいがぞう','Background image','Ảnh nền','','1','3',1)
,('アウトライン','','Outline','Ngoại tuyến,','','1','3',2)
,('アクセス','','Access','Truy cập','','1','3',2)
,('アクター','','Actor','Người làm','','1','3',2)
,('アサイン','','Assign','Phép gán','','1','3',2)
,('アドレス','','Address','Địa chỉ','','1','3',2)
,('レイアウト','','Layout','Bố cục','vd: sách, website','1','3',2)
,('テンプレート','','Template','Bản mẫu','','1','3',2)
,('インターフェース','','Interface','Giao diện','','1','3',2)

-- type:4 -> Nút xử lý
,('戻る','もどる','Return','Trở về','','1','4',1)
,('戻り値','もどりち','Return value','Giá trị trả về(của 1 function)','','1','4',1)
,('印刷','いんさつ','Print','In ấn, dấu','','1','4',1)
,('参照','さんしょう','Reference','Tham chiếu, tham khảo','','1','4',1)
,('更新','こうしん','Update','Gia hạn, đối mới, cập nhật','','1','4',1)
,('編集','へんしゅう','Edit','Biên tập','','1','4',1)
,('画面','がめん','Screen','Màn hình','','1','4',1)
,('検索','けんさく','Search','Tìm kiếm','','1','4',1)
,('新規','しんき','New','Mới lạ, mới mẻ','','1','4',1)
,('登録','とうろく','Registration','Đăng ký, sự đăng ký','','1','4',1)
,('新規登録','しんきとうろく','Sign up','Đăng ký mới','','1','4',1)
,('修正','しゅうせい','Fix','Tu sửa, đính chính','','1','4',1)
,('一覧','いちらん','List','Danh sách','','1','4',1)
,('追加','ついか','Add to','Sự thêm vào','','1','4',1)
,('開く','ひらく','Open','Mở','','1','4',1)
,('確認','かくにん','Confirmation','Xác nhận','','1','4',1)
,('画像','がぞう','Image','Hình tượng, hình ảnh','','1','4',1)
,('解除','かいじょ','Cancel','Hủy bỏ','','1','4',1)
,('障害','しょうがい','Disability','Trở ngại, chướng ngại','','1','4',1)
,('変更','へんこう','Change','Biến đổi, thay đổi','','1','4',1)
,('仕様書','しようしょ','Specifications','Bảng thiết kế (document)','','1','4',1)
,('削除','さくじょ','Delete','Xóa bỏ, gạch bỏ','','1','4',1)
,('項目','こうもく','Item','Hạng mục, điều khoản','','1','4',1)
,('接続','せつぞく','Connection','Sự nối, liên hệ','','1','4',1)
,('貼り付け','はりつけ','Paste','Dán vào, gắn vào( file vi tính)','','1','4',1)
,('降順','こうじゅん','Descending order(DESC)','Sắp xếp giảm dần','','1','4',1)
,('昇順','しょうじゅん','Ascending order(ASC)','Sắp xếp tăng dần','','1','4',1)
,('投稿','とうこう','Post','Đăng bài, cộng tác viên','','1','4',1)
,('購読','こうどく','Subscribe','Theo dõi, đăng ký','','1','4',1)
,('公開','こうかい','Public','Công khai','','1','4',1)
,('埋め込む','うめこむ','Embed','Nhúng','','1','4',1)
,('もっと見る','','','Tìm hiểu thêm','','1','4',1)
,('破棄','はき','Discard','Hủy bỏ, hủy','','1','4',1)
,('アンドゥ','','Undo','Lui lại, lùi về','','1','4',2)

-- type:5 -> Thiết bị & Phần cứng
,('ハードウェア','','Hardware','Phần cứng','','1','5',2)
,('システム','','System','Hệ thống','','1','5',2)
,('機械','きかい','Hardware','Máy móc','','1','5',1)
,('オーエス','','OS（Operating System）','Hệ điều hành','','1','5',2)
,('アンド・ロイド','','Android','Hệ điều hành Android','','1','5',2)
,('アイ・オーエス','','IOS','Hệ điều hành IOS','','1','5',2)
,('ウィンドウズ','','Windows','Hệ điều hành Windows','','1','5',2)
,('マックオーエス','','MacOS','Hệ điều hành MacOS','','1','5',2)
,('リナックス','','Linux','Hệ điều hành Linux','','1','5',2)
,('ユニックス','','Unix','Hệ điều hành Unix','','1','5',2)
-- type:6 -> Tài liệu thiết kết
,('システム提案','','System proposal','Đề xuất hệ thống','','1','6',3)
,('要件定義','','Requirement definition','Định nghĩa yêu cầu','','1','6',1)
,('基本設計','','Basic design','Thiết kế cơ bản','','1','6',1)
,('機能設計','','Function design','Thiết kế chức năng','','1','6',1)
,('詳細設計','','Detail design','Thiết kế chi tiết','','1','6',1)
,('要求分析','','Requirement analysis','Thiết kế chi tiết','','1','6',1)
,('外部設計','','External design','Thiết kế bên ngoài','','1','6',1)
,('内部設計','','Internal design','Thiết kế bên trong','','1','6',1)
,('業務フロー','','Business flow','Luồng kinh doanh','','1','6',1)
,('システム構成図','','System configuration diagram','Sơ đồ cấu hình hệ thống','','1','6',3)
,('ER図','','ER diagram','Sơ đồ ER','','1','6',3)
,('設計書記述様式','','Design description style','Kiểu mô tả thiết kế','','1','6',1)
,('帳票','','Form','Biểu mẫu','','1','6',1)
,('画面遷移図','','Screen transition diagram','Sơ đồ chuyển đổi màn hình','','1','6',1)
,('段階','だんかい','Phase','Giai đoạn','','1','6',1)
,('フェーズ','','Phase','Giai đoạn','','1','6',2)
,('ステップ','','Step','Bước','','1','6',2)

-- type:10 -> Application
,('エクセル','','Excel','Bảng tính excel','','1','10',2)
,('インターネット・エクスプローラー','','Internet explorer','Trình duyệt IE','','1','10',2)

-- type:11 -> Xoạn thảo

-- type:12 -> Tên riêng
,('ビーツーシー版','ビーツーシーばん','B2C','Business to Customer','','1','12',3)
-- ,('ビジネス・トゥ・コンシューマー','','Business to Customer','Business to Customer','','1','12',2)
,('ビーツービー版','ビーツービーばん','B2B','Business to Business','','1','12',3)
-- ,('ビジネス・トゥ・ビジネス','','Business to Business','Business to Business','','1','12',2)
,('シーツーシー版','シーツーシーばん','C2C','Business to Business','','1','12',3)
-- ,('コンシューマー・トゥ・コンシューマー','','Customer to Customer','Customer to Customer','','1','12',2)

-- type:13 -> Khác
,('カテゴリ','','Category','Danh mục','','1','13',2)
,('タグ','','Tag','Thẻ từ khoá','','1','13',2)
,('キャッチコピー','','Catch copy/Edit','Chỉnh sửa','VD: Chỉnh sửa bài viết, comment…)','1','13',2)
,('モバイルコンテンツ向け','モバイルコンテンツむけ','','Xây dựng nội dung tương thích với bản mobile','','1','13',3)
,('タブ','','Tab','Mở tab mới trên trình duyệt','','1','13',2)
,('領域','りょういき','Region,area','Vị trí, khu vực','','1','13',1)
,('ナビゲーション','','Navigation','Điều hướng','Thường để chỉ khu vực thanh menu của page','1','13',3)
,('構成要素','こうせいようそ','Component','Các thành phần cấu tạo','','1','13',1)
,('空白','くうはく','Blank','Khoảng trống','','1','13',1)
,('ブランク','','Blank','Khoảng trống','','1','13',2)
,('空間','くうかん','Space','Khoảng trống','','1','13',1)
,('スペース','','Space','Khoảng trống','','1','13',2)
,('仕組み','しくみ','','Cơ cấu, tổ chức, cơ chế','','1','13',1)
,('添付','てんぷ','Attachment','Đính kèm','','1','13',3)
,('ファイル','','File','Tập tin','','1','13',3)

,('電子商取引','でんししょうとりひき','Electronic commerce','Thương mại điện tử','','1','13',3)
,('Eコマース','でんししょうとりひき','E-commerce','E-Commerce','','1','13',3)
,('メリット','','Merit','Ưu điểm, điểm mạnh','','1','13',2)
,('デメリット','','Demerit','Điểm hạn chế','','1','13',2)
,('カスタマイズ','','Customize','Tuỳ chỉnh','','1','13',2)
,('ソースの改変','~かいへん','Source modification','Điều chỉnh source code','','1','13',3)
,('セキュリティホール','','Security hole','Lỗ hổng bảo mật','','1','13',2)
,('閲覧','えつらん','Browse','Đọc, duyệt (web), lướt (net)','','1','13',1)
,('ユーザーの振る舞い','〜ふるまい','','Hành vi enduser trên trang web','','1','13',3)
,('おすすめ記事','','Suggested articles','Bài viết đề cử','','1','13',1)
,('反復','はんぷく','Repetition','Vòng lặp','','1','13',1)
,('色のトーン','いろ~','Color tone','Tông màu','','1','13',3)
,('程度近い色同士','ていどちかいいろどうし','','Nhóm màu sắc tương đồng','','1','13',1)
,('イラスト','','Illustrate','Hình minh hoạ','','1','13',2)
,('遷移','せんい','Transition, Redirect','Sự chuyển trang','(Mở trang mới sau khi click vào đường dẫn)','1','13',1)
,('画面遷移時','がめんせんい','','Lúc load screen mới, screen transition','','1','13',1)
,('ページ遷移時','ページせんいじ','Page transition','Load page mới','','1','13',3)
,('ドロップシャドウ','','Drop shadow','Hiệu ứng đổ bóng','','1','13',2)
,('角が丸まった四角ボタン','つのがまるまったしかくボタン','','Nút với 4 góc bo tròn','','1','13',3)
,('見た目','みため','Appearance','Hình thức','','1','13',1)
,('アニメーション','','Animation','Hiệu ứng hoạt hình','','1','13',3)
,('見出し','みだし','Headline','Đầu mục','','1','13',1)
,('マシンリーダブル','','Machine readable','Có thể đọc được','(nôm na là hệ thống đọc & hiểu đc code của bạn)','1','13',2)
,('指定ページ','してい~','','Trang được chỉ định, trang đích','','1','13',3)
,('詳しくはこちら','くわし~','','Tìm hiểu thêm','','1','13',1)
,('よくある質問','','','Câu hỏi thường gặp','','1','13',1)
,('規約','きやく','Terms','Điều khoản','','1','13',1)
,('利用規約','りようきやく','Terms of service','Điều khoản sử dụng','','1','13',1)
,('最新記事','さいしんきじ','','Bài viết mới nhất','','1','13',1)
,('続きを読む','つづきをよむ','','Đọc tiếp','','1','13',1)
,('関連記事','かんれんきじ','','Bài iết liên quan','','1','13',1)
,('当サイト','とう〜','','Trang này','','1','13',3)
,('ブログ','','Blog','','','1','13',2)
,('ヘルプ','','Help','Trợ giúp','','1','13',2)
,('ニュース','','News','Tin tức','','1','13',2)
,('キャリア','','Career','Công việc','','1','13',2)
,('人気記事','にんききじ','Popular articles','Được xem nhiều nhất','','1','13',1)
,('元に戻す','もとにもどす','','Lui lại, lùi về','','1','13',1)
,('構成','こうせい','Constitution','Cấu trúc','','1','13',1)
,('ガイド','','Guide','Hướng dẫn','','1','13',2)
,('余り','あまり','','Chia lấy dư','','1','13',1)
,('暗黙','あんもく','','Mặc định ngầm','','1','13',1)

,('アプリ','','Application','Ứng dụng','','1','13',2)
,('アプリケーション','','Application','Ứng dụng','','1','13',2)
,('アプローチ','','Approach','Tiếp cận','','1','13',2)
,('アンケート','','Questionnaire','Thuật hỏi, bảng hỏi','','1','13',2)
,('イメージ','','Image','Sự phản ảnh, tạo ảnh','','1','13',2)
,('インストール','','Install','Tiết lập, lắp ráp','','1','13',2)
,('インターネット','','Internet','Liên mạng','','1','13',2)
,('イントラネット','','Intranet','Mạng cục bộ, mạng nội bộ','','1','13',2)
,('インフラ','','Infrastructure','Cấu trúc hạ tầng','','1','13',2)
,('インプリメンテーション','','Implementation','Thực hiện, cài đặt','','1','13',2)
,('エラー','','Error','Lỗi','','1','13',2)
,('エンドユーザ','','End user','Người dung cuối','','1','13',2)
,('オブジェクト','','Object','Biến đối tượng','','1','13',2)
,('オプション','','Option','Sự lựa chọn','','1','13',2)
,('オペレータ','','Operator','Điều hành','','1','13',2)
,('キャラクター','','Character','nhân vật','','1','13',2)

;
UPDATE vocabulary set created = now(), modified = now() where created is null;
UPDATE vocabulary set word_of_day = now() where id <= 10;